<a href="https://colab.research.google.com/github/klaudiaajuszczykk/data-science-bootcamp/blob/main/%C4%87wiczenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello colab")

hello colab

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
### Series

In [ ]:
s=pd.Series(data=[3., 2, 4, 6], index=["a", "b", "c", "d"], name="sample")
s

a    3.0
b    2.0
c    4.0
d    6.0
Name: sample, dtype: float64

In [ ]:
import numpy as np

In [ ]:
np.nan

nan

In [ ]:
s=pd.Series(data=[3., np.nan, 4, 6], index=["a", "b", "c", "d"], name="sample")
s

a    3.0
b    NaN
c    4.0
d    6.0
Name: sample, dtype: float64

In [ ]:
s=pd.Series(data=[True, False, False])
s

0     True
1    False
2    False
dtype: bool

In [ ]:
from numpy._core.defchararray import index
s=pd.Series(data=np.arange(10,20), index=pd.date_range(start="20200101", periods=10), name="daty")
s

2020-01-01    10
2020-01-02    11
2020-01-03    12
2020-01-04    13
2020-01-05    14
2020-01-06    15
2020-01-07    16
2020-01-08    17
2020-01-09    18
2020-01-10    19
Freq: D, Name: daty, dtype: int64

In [ ]:
import pandas as pd

In [ ]:
s.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
list(s.index)

[Timestamp('2020-01-01 00:00:00'),
 Timestamp('2020-01-02 00:00:00'),
 Timestamp('2020-01-03 00:00:00'),
 Timestamp('2020-01-04 00:00:00'),
 Timestamp('2020-01-05 00:00:00'),
 Timestamp('2020-01-06 00:00:00'),
 Timestamp('2020-01-07 00:00:00'),
 Timestamp('2020-01-08 00:00:00'),
 Timestamp('2020-01-09 00:00:00'),
 Timestamp('2020-01-10 00:00:00')]

In [ ]:
s=pd.Series(data=['python', 'java', 'sql'], name='languages')
s

0    python
1      java
2       sql
Name: languages, dtype: object

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
s.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.dtype(s)

dtype('int64')

In [ ]:
s.shape

(10,)

In [ ]:
price=pd.Series(data={'Apple': 200, 'CD Project':60, 'Amazon':1900, 'KGHM':np.nan})
price

Apple          200.0
CD Project      60.0
Amazon        1900.0
KGHM             NaN
dtype: float64

In [ ]:
price['CD Project']

np.int64(60)

In [ ]:
price[1]

/tmp/ipykernel_1766/4074423798.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  price[1]

np.int64(60)

In [ ]:
price.count()

np.int64(3)

In [ ]:
price.value_counts(dropna=False)

200.0     1
60.0      1
1900.0    1
NaN       1
Name: count, dtype: int64

In [ ]:
price.sum()

np.int64(2160)

In [ ]:
price.min()

60

In [ ]:
price.max()

1900

In [ ]:
price.std()

1024.3046421841502

In [ ]:
price.describe()

count       3.000000
mean      720.000000
std      1024.304642
min        60.000000
25%       130.000000
50%       200.000000
75%      1050.000000
max      1900.000000
dtype: float64

In [ ]:
price.nlargest(2)

Amazon    1900.0
Apple      200.0
dtype: float64

In [ ]:
price.nsmallest(2)

CD Project     60.0
Apple         200.0
dtype: float64

In [ ]:
price.sort_values(ascending=False)

Amazon        1900.0
Apple          200.0
CD Project      60.0
KGHM             NaN
dtype: float64

In [ ]:
 price_pln=price.apply(lambda x: x*3.8)

In [ ]:
price_pln

Apple          760.0
CD Project     228.0
Amazon        7220.0
KGHM             NaN
dtype: float64

In [4]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(data=[[10,12,13],[23,12,10]], index=['first', 'second'], columns=['col_1', 'col_2', 'col_3'])
df

        col_1  col_2  col_3
first      10     12     13
second     23     12     10

In [7]:
df['col_1']

first     10
second    23
Name: col_1, dtype: int64